#!/bin/bash


config_file=".config"
header_file="config.h"

echo "// Automatically generated by config_to_header.sh" >> $header_file
echo "// Do not edit manually" >> $header_file

while read -r line || [[ -n "$line" ]]; do
    if [[ $line == CONFIG_* ]]; then
        config=$(echo "$line" | cut -d '=' -f1)
        echo "#define $config 1" >> $header_file
    fi
done < "$config_file"

echo "Generated $header_file from $config_file"

