#!/bin/bash


config_file=".config"
header_file="config.h"

if [[ -f $header_file ]]; then
    rm $header_file
fi

echo "// Automatically generated by config_to_header.sh" >> $header_file
echo "// Do not edit manually" >> $header_file

while read -r line || [[ -n "$line" ]]; do
    if [[ $line == CONFIG_* ]]; then
        config=$(echo "$line" | cut -d '=' -f1)
        value=$(echo "$line" | cut -d '=' -f2)
        echo "#define $config $value" >> $header_file
    fi
done < "$config_file"

echo "Generated $header_file from $config_file"

